/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/maps/map.glb -o src/components/map.tsx -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCylinder35_color_0: THREE.Mesh
    snowflakes1_color_0: THREE.Mesh
    snowflakes2_color_0: THREE.Mesh
    snowflakes3_color_0: THREE.Mesh
    floor_color_0: THREE.Mesh
    house1_color_0: THREE.Mesh
    house_01_color_0: THREE.Mesh
    house_02_color_0: THREE.Mesh
    house_03_color_0: THREE.Mesh
    house_04_color_0: THREE.Mesh
    house_05_color_0: THREE.Mesh
    house_06_color_0: THREE.Mesh
    house_07_color_0: THREE.Mesh
    house_08_color_0: THREE.Mesh
    house_09_color_0: THREE.Mesh
    pPlane62_color_0: THREE.Mesh
    pPlane63_color_0: THREE.Mesh
    pPlane64_color_0: THREE.Mesh
    pPlane65_color_0: THREE.Mesh
    pPlane66_color_0: THREE.Mesh
    pPlane67_color_0: THREE.Mesh
    pPlane68_color_0: THREE.Mesh
    pPlane69_color_0: THREE.Mesh
    pPlane70_color_0: THREE.Mesh
    pPlane71_color_0: THREE.Mesh
    railway_color_0: THREE.Mesh
    segway_color_0: THREE.Mesh
    segway1_color_0: THREE.Mesh
    segway2_color_0: THREE.Mesh
    segway3_color_0: THREE.Mesh
    sky_color_0: THREE.Mesh
    star_color_0: THREE.Mesh
    star1_color_0: THREE.Mesh
    star10_color_0: THREE.Mesh
    star11_color_0: THREE.Mesh
    star2_color_0: THREE.Mesh
    star3_color_0: THREE.Mesh
    star4_color_0: THREE.Mesh
    star5_color_0: THREE.Mesh
    star6_color_0: THREE.Mesh
    star7_color_0: THREE.Mesh
    star8_color_0: THREE.Mesh
    star9_color_0: THREE.Mesh
    star_color_0001: THREE.Mesh
    star1_color_0001: THREE.Mesh
    star10_color_0001: THREE.Mesh
    star11_color_0001: THREE.Mesh
    star2_color_0001: THREE.Mesh
    star3_color_0001: THREE.Mesh
    star4_color_0001: THREE.Mesh
    star5_color_0001: THREE.Mesh
    star6_color_0001: THREE.Mesh
    star7_color_0001: THREE.Mesh
    star8_color_0001: THREE.Mesh
    star9_color_0001: THREE.Mesh
    star_color_0002: THREE.Mesh
    star1_color_0002: THREE.Mesh
    star10_color_0002: THREE.Mesh
    star11_color_0002: THREE.Mesh
    star2_color_0002: THREE.Mesh
    star3_color_0002: THREE.Mesh
    star4_color_0002: THREE.Mesh
    star5_color_0002: THREE.Mesh
    star6_color_0002: THREE.Mesh
    star7_color_0002: THREE.Mesh
    star8_color_0002: THREE.Mesh
    star9_color_0002: THREE.Mesh
    star_color_0003: THREE.Mesh
    star1_color_0003: THREE.Mesh
    star10_color_0003: THREE.Mesh
    star11_color_0003: THREE.Mesh
    star2_color_0003: THREE.Mesh
    star3_color_0003: THREE.Mesh
    star4_color_0003: THREE.Mesh
    star5_color_0003: THREE.Mesh
    star6_color_0003: THREE.Mesh
    star7_color_0003: THREE.Mesh
    star8_color_0003: THREE.Mesh
    star9_color_0003: THREE.Mesh
    star_color_0004: THREE.Mesh
    star1_color_0004: THREE.Mesh
    star10_color_0004: THREE.Mesh
    star11_color_0004: THREE.Mesh
    star2_color_0004: THREE.Mesh
    star3_color_0004: THREE.Mesh
    star4_color_0004: THREE.Mesh
    star5_color_0004: THREE.Mesh
    star6_color_0004: THREE.Mesh
    star7_color_0004: THREE.Mesh
    star8_color_0004: THREE.Mesh
    star9_color_0004: THREE.Mesh
    Train_A_color_0: THREE.Mesh
    train_B_color_0: THREE.Mesh
    train_C_color_0: THREE.Mesh
    tree_01_color_0: THREE.Mesh
    tree_010_color_0: THREE.Mesh
    tree_011_color_0: THREE.Mesh
    tree_012_color_0: THREE.Mesh
    tree_013_color_0: THREE.Mesh
    tree_014_color_0: THREE.Mesh
    tree_015_color_0: THREE.Mesh
    tree_02_color_0: THREE.Mesh
    tree_025_color_0: THREE.Mesh
    tree_026_color_0: THREE.Mesh
    tree_027_color_0: THREE.Mesh
    tree_028_color_0: THREE.Mesh
    tree_029_color_0: THREE.Mesh
    tree_03_color_0: THREE.Mesh
    tree_030_color_0: THREE.Mesh
    tree_031_color_0: THREE.Mesh
    tree_032_color_0: THREE.Mesh
    tree_033_color_0: THREE.Mesh
    tree_034_color_0: THREE.Mesh
    tree_035_color_0: THREE.Mesh
    tree_036_color_0: THREE.Mesh
    tree_037_color_0: THREE.Mesh
    tree_038_color_0: THREE.Mesh
    tree_04_color_0: THREE.Mesh
    tree_05_color_0: THREE.Mesh
    tree_06_color_0: THREE.Mesh
    tree_07_color_0: THREE.Mesh
    tree_08_color_0: THREE.Mesh
    tree_09_color_0: THREE.Mesh
  }
  materials: {
    ['color.002']: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/maps/map.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-167.01, 19.63, 79.399]}>
        <mesh geometry={nodes.pCylinder35_color_0.geometry} material={materials['color.002']} scale={4.234} />
        <mesh geometry={nodes.snowflakes1_color_0.geometry} material={materials['color.002']} position={[0, 2.152, 0.588]} scale={[0.268, 0.276, 0.277]} />
        <mesh geometry={nodes.snowflakes2_color_0.geometry} material={materials['color.002']} position={[2.201, 0.622, 1.224]} scale={[0.337, 0.347, 0.349]} />
        <mesh geometry={nodes.snowflakes3_color_0.geometry} material={materials['color.002']} position={[3.18, 1.847, -0.001]} scale={[0.187, 0.192, 0.193]} />
      </group>
      <group position={[-35.903, 0, 109.583]} rotation={[0, -1.308, 0]}>
        <mesh geometry={nodes.star_color_0001.geometry} material={materials['color.002']} position={[-786.321, 506.564, 113.809]} rotation={[0.126, 0.222, -2.175]} scale={14.07} />
        <mesh geometry={nodes.star1_color_0001.geometry} material={materials['color.002']} position={[-745.61, 523.071, -69.901]} rotation={[0.017, 0.037, -2.147]} scale={27.136} />
        <mesh geometry={nodes.star10_color_0001.geometry} material={materials['color.002']} position={[-694.746, 524.676, -321.092]} rotation={[-0.386, -0.111, -2.064]} scale={7.669} />
        <mesh geometry={nodes.star11_color_0001.geometry} material={materials['color.002']} position={[-710.531, 584.391, 25.691]} rotation={[-0.206, 0.274, -2.439]} scale={7.102} />
        <mesh geometry={nodes.star2_color_0001.geometry} material={materials['color.002']} position={[-803.708, 208.196, -110.666]} rotation={[-0.108, 0.038, -1.904]} scale={6.812} />
        <mesh geometry={nodes.star3_color_0001.geometry} material={materials['color.002']} position={[-775.714, 334.223, -333.555]} rotation={[0.425, -0.143, -1.875]} scale={17.713} />
        <mesh geometry={nodes.star4_color_0001.geometry} material={materials['color.002']} position={[-781.69, 411.2, 214.065]} rotation={[0.166, 0.319, -2.095]} scale={8.137} />
        <mesh geometry={nodes.star5_color_0001.geometry} material={materials['color.002']} position={[-640.456, 410.877, -430.282]} rotation={[-0.272, -0.296, -2.094]} scale={17.24} />
        <mesh geometry={nodes.star6_color_0001.geometry} material={materials['color.002']} position={[-799.651, 144.737, 201.077]} rotation={[0.126, 0.222, -2.175]} scale={5.757} />
        <mesh geometry={nodes.star7_color_0001.geometry} material={materials['color.002']} position={[-771.386, 466.649, -207.941]} rotation={[0.957, -0.113, -1.489]} scale={7.158} />
        <mesh geometry={nodes.star8_color_0001.geometry} material={materials['color.002']} position={[-782.532, 138.463, -399.259]} rotation={[1.022, -0.317, -1.669]} scale={5.277} />
        <mesh geometry={nodes.star9_color_0001.geometry} material={materials['color.002']} position={[-784.674, 310.553, 31.15]} rotation={[0.505, 0.018, -1.768]} scale={8.137} />
      </group>
      <group position={[10.801, 0, -17.044]} rotation={[0, 1.006, 0]}>
        <mesh geometry={nodes.star_color_0002.geometry} material={materials['color.002']} position={[-786.321, 506.564, 113.809]} rotation={[0.126, 0.222, -2.175]} scale={14.07} />
        <mesh geometry={nodes.star1_color_0002.geometry} material={materials['color.002']} position={[-745.61, 523.071, -69.901]} rotation={[0.017, 0.037, -2.147]} scale={27.136} />
        <mesh geometry={nodes.star10_color_0002.geometry} material={materials['color.002']} position={[-670.171, 567.849, -308.428]} rotation={[-0.386, -0.111, -2.064]} scale={7.669} />
        <mesh geometry={nodes.star11_color_0002.geometry} material={materials['color.002']} position={[-710.531, 584.391, 25.691]} rotation={[-0.206, 0.274, -2.439]} scale={7.102} />
        <mesh geometry={nodes.star2_color_0002.geometry} material={materials['color.002']} position={[-803.708, 208.196, -110.666]} rotation={[-0.108, 0.038, -1.904]} scale={6.812} />
        <mesh geometry={nodes.star3_color_0002.geometry} material={materials['color.002']} position={[-775.714, 334.223, -333.555]} rotation={[0.425, -0.143, -1.875]} scale={17.713} />
        <mesh geometry={nodes.star4_color_0002.geometry} material={materials['color.002']} position={[-781.69, 411.2, 214.065]} rotation={[0.166, 0.319, -2.095]} scale={8.137} />
        <mesh geometry={nodes.star5_color_0002.geometry} material={materials['color.002']} position={[-640.456, 410.877, -430.282]} rotation={[-0.272, -0.296, -2.094]} scale={17.24} />
        <mesh geometry={nodes.star6_color_0002.geometry} material={materials['color.002']} position={[-799.651, 144.737, 201.077]} rotation={[0.126, 0.222, -2.175]} scale={5.757} />
        <mesh geometry={nodes.star7_color_0002.geometry} material={materials['color.002']} position={[-771.386, 466.649, -207.941]} rotation={[0.957, -0.113, -1.489]} scale={7.158} />
        <mesh geometry={nodes.star8_color_0002.geometry} material={materials['color.002']} position={[-782.532, 138.463, -399.258]} rotation={[1.022, -0.317, -1.669]} scale={5.277} />
        <mesh geometry={nodes.star9_color_0002.geometry} material={materials['color.002']} position={[-784.674, 310.553, 31.15]} rotation={[0.505, 0.018, -1.768]} scale={8.137} />
      </group>
      <group position={[-82.725, 0, -139.827]} rotation={[-Math.PI, 0.962, -Math.PI]} scale={0.965}>
        <mesh geometry={nodes.star_color_0003.geometry} material={materials['color.002']} position={[-786.321, 506.564, 113.809]} rotation={[0.126, 0.222, -2.175]} scale={14.07} />
        <mesh geometry={nodes.star1_color_0003.geometry} material={materials['color.002']} position={[-745.61, 523.071, -69.901]} rotation={[0.017, 0.037, -2.147]} scale={27.136} />
        <mesh geometry={nodes.star10_color_0003.geometry} material={materials['color.002']} position={[-670.171, 567.849, -308.428]} rotation={[-0.386, -0.111, -2.064]} scale={7.669} />
        <mesh geometry={nodes.star11_color_0003.geometry} material={materials['color.002']} position={[-710.531, 584.391, 25.691]} rotation={[-0.206, 0.274, -2.439]} scale={7.102} />
        <mesh geometry={nodes.star2_color_0003.geometry} material={materials['color.002']} position={[-803.708, 208.196, -110.666]} rotation={[-0.108, 0.038, -1.904]} scale={6.812} />
        <mesh geometry={nodes.star3_color_0003.geometry} material={materials['color.002']} position={[-775.714, 334.223, -333.555]} rotation={[0.425, -0.143, -1.875]} scale={17.713} />
        <mesh geometry={nodes.star4_color_0003.geometry} material={materials['color.002']} position={[-781.69, 411.2, 214.065]} rotation={[0.166, 0.319, -2.095]} scale={8.137} />
        <mesh geometry={nodes.star5_color_0003.geometry} material={materials['color.002']} position={[-640.456, 410.877, -430.282]} rotation={[-0.272, -0.296, -2.094]} scale={17.24} />
        <mesh geometry={nodes.star6_color_0003.geometry} material={materials['color.002']} position={[-799.651, 144.737, 201.077]} rotation={[0.126, 0.222, -2.175]} scale={5.757} />
        <mesh geometry={nodes.star7_color_0003.geometry} material={materials['color.002']} position={[-771.386, 466.649, -207.941]} rotation={[0.957, -0.113, -1.489]} scale={7.158} />
        <mesh geometry={nodes.star8_color_0003.geometry} material={materials['color.002']} position={[-782.532, 138.463, -399.259]} rotation={[1.022, -0.317, -1.669]} scale={5.277} />
        <mesh geometry={nodes.star9_color_0003.geometry} material={materials['color.002']} position={[-784.674, 310.553, 31.15]} rotation={[0.505, 0.018, -1.768]} scale={8.137} />
      </group>
      <group position={[-197.514, 0, -51.928]} rotation={[Math.PI, -0.422, Math.PI]} scale={0.965}>
        <mesh geometry={nodes.star_color_0004.geometry} material={materials['color.002']} position={[-748.792, 481.308, 102.058]} rotation={[0.126, 0.222, -2.175]} scale={14.07} />
        <mesh geometry={nodes.star1_color_0004.geometry} material={materials['color.002']} position={[-745.61, 523.071, -69.901]} rotation={[0.017, 0.037, -2.147]} scale={27.136} />
        <mesh geometry={nodes.star10_color_0004.geometry} material={materials['color.002']} position={[-670.171, 567.849, -308.428]} rotation={[-0.386, -0.111, -2.064]} scale={7.669} />
        <mesh geometry={nodes.star11_color_0004.geometry} material={materials['color.002']} position={[-710.531, 584.391, 25.691]} rotation={[-0.206, 0.274, -2.439]} scale={7.102} />
        <mesh geometry={nodes.star2_color_0004.geometry} material={materials['color.002']} position={[-803.708, 208.196, -110.666]} rotation={[-0.108, 0.038, -1.904]} scale={6.812} />
        <mesh geometry={nodes.star3_color_0004.geometry} material={materials['color.002']} position={[-775.714, 334.223, -333.555]} rotation={[0.425, -0.143, -1.875]} scale={17.713} />
        <mesh geometry={nodes.star4_color_0004.geometry} material={materials['color.002']} position={[-743.261, 390.231, 197.695]} rotation={[0.166, 0.319, -2.095]} scale={8.137} />
        <mesh geometry={nodes.star5_color_0004.geometry} material={materials['color.002']} position={[-640.456, 410.877, -430.282]} rotation={[-0.272, -0.296, -2.094]} scale={17.24} />
        <mesh geometry={nodes.star6_color_0004.geometry} material={materials['color.002']} position={[-799.651, 144.737, 201.077]} rotation={[0.126, 0.222, -2.175]} scale={5.757} />
        <mesh geometry={nodes.star7_color_0004.geometry} material={materials['color.002']} position={[-771.386, 466.649, -207.941]} rotation={[0.957, -0.113, -1.489]} scale={7.158} />
        <mesh geometry={nodes.star8_color_0004.geometry} material={materials['color.002']} position={[-782.532, 138.463, -399.259]} rotation={[1.022, -0.317, -1.669]} scale={5.277} />
        <mesh geometry={nodes.star9_color_0004.geometry} material={materials['color.002']} position={[-784.674, 310.553, 31.15]} rotation={[0.505, 0.018, -1.768]} scale={8.137} />
      </group>
      <mesh geometry={nodes.floor_color_0.geometry} material={materials['color.002']} position={[-124.768, 0, -68.87]} scale={[1932.29, 1306.333, 1668.119]} />
      <mesh geometry={nodes.house1_color_0.geometry} material={materials['color.002']} />
      <mesh geometry={nodes.house_01_color_0.geometry} material={materials['color.002']} position={[-325.925, 0, 434.673]} rotation={[0, 0.449, 0]} />
      <mesh geometry={nodes.house_02_color_0.geometry} material={materials['color.002']} position={[-526.571, 0, -75.529]} rotation={[0, -0.221, 0]} />
      <mesh geometry={nodes.house_03_color_0.geometry} material={materials['color.002']} position={[-287.735, 0, -617.377]} rotation={[0, -1.498, 0]} />
      <mesh geometry={nodes.house_04_color_0.geometry} material={materials['color.002']} position={[365.264, 0, -617.743]} rotation={[Math.PI, -1.066, Math.PI]} />
      <mesh geometry={nodes.house_05_color_0.geometry} material={materials['color.002']} position={[634.006, 0, -56.086]} rotation={[Math.PI, -0.232, Math.PI]} />
      <mesh geometry={nodes.house_06_color_0.geometry} material={materials['color.002']} position={[435.849, 0, 471.758]} rotation={[-Math.PI, 1.146, -Math.PI]} />
      <mesh geometry={nodes.house_07_color_0.geometry} material={materials['color.002']} position={[112.411, 0, 472.243]} rotation={[-Math.PI, 0.939, -Math.PI]} />
      <mesh geometry={nodes.house_08_color_0.geometry} material={materials['color.002']} position={[-36.863, 0, 625.092]} rotation={[0, 0.968, 0]} />
      <mesh geometry={nodes.house_09_color_0.geometry} material={materials['color.002']} position={[11.917, 0, -467.049]} rotation={[Math.PI, -1.533, Math.PI]} />
      <mesh geometry={nodes.pPlane62_color_0.geometry} material={materials['color.002']} position={[-22.052, -5.904, 43.912]} />
      <mesh geometry={nodes.pPlane63_color_0.geometry} material={materials['color.002']} position={[-22.052, -5.904, -37.835]} />
      <mesh geometry={nodes.pPlane64_color_0.geometry} material={materials['color.002']} position={[-130.724, -8.698, -37.835]} />
      <mesh geometry={nodes.pPlane65_color_0.geometry} material={materials['color.002']} position={[-130.724, -8.698, 43.912]} />
      <mesh geometry={nodes.pPlane66_color_0.geometry} material={materials['color.002']} position={[-450.356, -7.164, 34.339]} rotation={[0, -0.189, 0]} />
      <mesh geometry={nodes.pPlane67_color_0.geometry} material={materials['color.002']} position={[-242.786, -5.497, 388.583]} rotation={[0, 0.489, 0]} />
      <mesh geometry={nodes.pPlane68_color_0.geometry} material={materials['color.002']} position={[311.968, -5.904, 389.786]} rotation={[0, -0.592, 0]} />
      <mesh geometry={nodes.pPlane69_color_0.geometry} material={materials['color.002']} position={[444.605, -5.904, 420.609]} rotation={[-Math.PI, 0.181, -Math.PI]} />
      <mesh geometry={nodes.pPlane70_color_0.geometry} material={materials['color.002']} position={[428.109, -5.904, 380.416]} rotation={[0, 1.393, 0]} />
      <mesh geometry={nodes.pPlane71_color_0.geometry} material={materials['color.002']} position={[270.732, -5.904, -584.841]} rotation={[Math.PI, -1.533, Math.PI]} />
      <mesh geometry={nodes.railway_color_0.geometry} material={materials['color.002']} position={[-6.106, 0, 9.364]} />
      <mesh geometry={nodes.segway_color_0.geometry} material={materials['color.002']} position={[-165.178, 26.966, -215.012]} scale={[11.754, 42.174, 4.383]} />
      <mesh geometry={nodes.segway1_color_0.geometry} material={materials['color.002']} position={[-165.178, 26.966, -274.679]} scale={[11.754, 42.174, 4.383]} />
      <mesh geometry={nodes.segway2_color_0.geometry} material={materials['color.002']} position={[-165.178, 26.966, -332.955]} scale={[11.754, 42.174, 4.383]} />
      <mesh geometry={nodes.segway3_color_0.geometry} material={materials['color.002']} position={[-165.178, 26.966, -131.749]} scale={[11.754, 42.174, 4.383]} />
      <mesh geometry={nodes.sky_color_0.geometry} material={materials['color.002']} position={[-122.751, 0, 0]} scale={872.069} />
      <mesh geometry={nodes.star_color_0.geometry} material={materials['color.002']} position={[-786.321, 506.564, 113.809]} rotation={[0.126, 0.222, -2.175]} scale={14.07} />
      <mesh geometry={nodes.star1_color_0.geometry} material={materials['color.002']} position={[-745.61, 523.071, -69.901]} rotation={[0.017, 0.037, -2.147]} scale={27.136} />
      <mesh geometry={nodes.star10_color_0.geometry} material={materials['color.002']} position={[-670.171, 567.849, -308.428]} rotation={[-0.386, -0.111, -2.064]} scale={7.669} />
      <mesh geometry={nodes.star11_color_0.geometry} material={materials['color.002']} position={[-710.531, 584.391, 25.691]} rotation={[-0.206, 0.274, -2.439]} scale={7.102} />
      <mesh geometry={nodes.star2_color_0.geometry} material={materials['color.002']} position={[-803.708, 208.196, -110.666]} rotation={[-0.108, 0.038, -1.904]} scale={6.812} />
      <mesh geometry={nodes.star3_color_0.geometry} material={materials['color.002']} position={[-775.714, 334.223, -333.555]} rotation={[0.425, -0.143, -1.875]} scale={17.713} />
      <mesh geometry={nodes.star4_color_0.geometry} material={materials['color.002']} position={[-781.69, 411.2, 214.065]} rotation={[0.166, 0.319, -2.095]} scale={8.137} />
      <mesh geometry={nodes.star5_color_0.geometry} material={materials['color.002']} position={[-640.456, 410.877, -430.282]} rotation={[-0.272, -0.296, -2.094]} scale={17.24} />
      <mesh geometry={nodes.star6_color_0.geometry} material={materials['color.002']} position={[-799.651, 144.737, 201.077]} rotation={[0.126, 0.222, -2.175]} scale={5.757} />
      <mesh geometry={nodes.star7_color_0.geometry} material={materials['color.002']} position={[-771.386, 466.649, -207.941]} rotation={[0.957, -0.113, -1.489]} scale={7.158} />
      <mesh geometry={nodes.star8_color_0.geometry} material={materials['color.002']} position={[-782.532, 138.463, -399.259]} rotation={[1.022, -0.317, -1.669]} scale={5.277} />
      <mesh geometry={nodes.star9_color_0.geometry} material={materials['color.002']} position={[-784.674, 310.553, 31.15]} rotation={[0.505, 0.018, -1.768]} scale={8.137} />
      <mesh geometry={nodes.Train_A_color_0.geometry} material={materials['color.002']} position={[-167.032, 12.526, 68.796]} />
      <mesh geometry={nodes.train_B_color_0.geometry} material={materials['color.002']} position={[-167.032, 10.579, 31.365]} />
      <mesh geometry={nodes.train_C_color_0.geometry} material={materials['color.002']} position={[-167.032, 10.579, -10.07]} />
      <mesh geometry={nodes.tree_01_color_0.geometry} material={materials['color.002']} position={[-104.044, 51.262, -49.172]} rotation={[0, 0.569, -Math.PI / 2]} scale={[105.137, 70.733, 43.56]} />
      <mesh geometry={nodes.tree_010_color_0.geometry} material={materials['color.002']} position={[-50.163, 48.226, 429.037]} rotation={[0, 0.545, -Math.PI / 2]} scale={[100.867, 80.685, 39.473]} />
      <mesh geometry={nodes.tree_011_color_0.geometry} material={materials['color.002']} position={[-389.156, 42.586, 217.813]} rotation={[0, 0.184, -Math.PI / 2]} scale={[88.426, 70.733, 34.605]} />
      <mesh geometry={nodes.tree_012_color_0.geometry} material={materials['color.002']} position={[-819.488, 48.226, -118.381]} rotation={[0, -0.842, -Math.PI / 2]} scale={[100.867, 80.685, 39.473]} />
      <mesh geometry={nodes.tree_013_color_0.geometry} material={materials['color.002']} position={[-521.151, 56.51, 76.893]} rotation={[0, -0.254, -Math.PI / 2]} scale={[119.135, 95.298, 46.622]} />
      <mesh geometry={nodes.tree_014_color_0.geometry} material={materials['color.002']} position={[-501.54, 42.586, -102.168]} rotation={[0, -0.531, -Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_015_color_0.geometry} material={materials['color.002']} position={[-762.871, 42.586, -363.926]} rotation={[0, -0.531, -Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_02_color_0.geometry} material={materials['color.002']} position={[-325.794, 75.992, 331.556]} rotation={[0, 0.702, -Math.PI / 2]} scale={[160.203, 128.148, 62.694]} />
      <mesh geometry={nodes.tree_025_color_0.geometry} material={materials['color.002']} position={[-402.405, 75.992, -533.23]} rotation={[-Math.PI, -1.194, Math.PI / 2]} scale={[160.203, 128.148, 49.208]} />
      <mesh geometry={nodes.tree_026_color_0.geometry} material={materials['color.002']} position={[-86.862, 42.586, -738.508]} rotation={[0, -1.061, -Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_027_color_0.geometry} material={materials['color.002']} position={[150.759, 42.586, -378.794]} rotation={[Math.PI, -0.872, Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_028_color_0.geometry} material={materials['color.002']} position={[-118.038, 42.586, -239.338]} rotation={[-Math.PI, -1.526, Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_029_color_0.geometry} material={materials['color.002']} position={[371.901, 42.586, -504.488]} rotation={[-Math.PI, -1.226, Math.PI / 2]} scale={[88.426, 70.733, 31.501]} />
      <mesh geometry={nodes.tree_03_color_0.geometry} material={materials['color.002']} position={[-275.514, 51.262, -48.071]} rotation={[-Math.PI, 1.117, Math.PI / 2]} scale={[105.137, 70.733, 43.56]} />
      <mesh geometry={nodes.tree_030_color_0.geometry} material={materials['color.002']} position={[460.893, 42.586, -254.67]} rotation={[-Math.PI, -0.791, Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_031_color_0.geometry} material={materials['color.002']} position={[540.624, 76.674, 162.968]} rotation={[-Math.PI, 0.134, Math.PI / 2]} scale={[158.507, 126.792, 48.687]} />
      <mesh geometry={nodes.tree_032_color_0.geometry} material={materials['color.002']} position={[305.02, 42.586, 299.429]} rotation={[-Math.PI, 0.513, Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_033_color_0.geometry} material={materials['color.002']} position={[-263.534, 42.586, 579]} rotation={[0, 1.398, -Math.PI / 2]} scale={[88.426, 70.733, 34.605]} />
      <mesh geometry={nodes.tree_034_color_0.geometry} material={materials['color.002']} position={[368.834, 42.586, 582.118]} rotation={[-Math.PI, 0.968, Math.PI / 2]} scale={[88.426, 70.733, 34.605]} />
      <mesh geometry={nodes.tree_035_color_0.geometry} material={materials['color.002']} position={[0.479, 75.992, -200.565]} rotation={[0, -0.774, -Math.PI / 2]} scale={[160.203, 128.148, 49.208]} />
      <mesh geometry={nodes.tree_036_color_0.geometry} material={materials['color.002']} position={[292.708, 76.674, -285.22]} rotation={[Math.PI, -0.135, Math.PI / 2]} scale={[158.507, 126.792, 56.466]} />
      <mesh geometry={nodes.tree_037_color_0.geometry} material={materials['color.002']} position={[296.652, 42.586, -89.217]} rotation={[Math.PI, -1.433, Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_038_color_0.geometry} material={materials['color.002']} position={[118.262, 76.674, -648.3]} rotation={[Math.PI, -1.283, Math.PI / 2]} scale={[158.507, 126.792, 48.687]} />
      <mesh geometry={nodes.tree_04_color_0.geometry} material={materials['color.002']} position={[-257.685, 56.903, 125.084]} rotation={[0, -0.976, -Math.PI / 2]} scale={[119.929, 80.685, 49.689]} />
      <mesh geometry={nodes.tree_05_color_0.geometry} material={materials['color.002']} position={[-82.028, 51.262, 128.294]} rotation={[Math.PI, 0.869, Math.PI / 2]} scale={[105.137, 70.733, 43.56]} />
      <mesh geometry={nodes.tree_06_color_0.geometry} material={materials['color.002']} position={[-676.978, 42.586, 166.606]} rotation={[0, -0.531, -Math.PI / 2]} scale={[88.426, 70.733, 27.161]} />
      <mesh geometry={nodes.tree_07_color_0.geometry} material={materials['color.002']} position={[93.73, 48.226, 508.029]} rotation={[-Math.PI, 1.454, Math.PI / 2]} scale={[100.867, 80.685, 39.473]} />
      <mesh geometry={nodes.tree_08_color_0.geometry} material={materials['color.002']} position={[-564.284, 62.15, 406]} rotation={[0, 0.232, -Math.PI / 2]} scale={[135.897, 108.706, 41.742]} />
      <mesh geometry={nodes.tree_09_color_0.geometry} material={materials['color.002']} position={[-225.706, 42.586, 237]} rotation={[0, -0.418, -Math.PI / 2]} scale={[88.426, 70.733, 34.605]} />
    </group>
  )
}

useGLTF.preload('/maps/map.glb')
